name: core_auto_update

on: 
#   release:
#       types: [published]
#   push:
#       tags:
#       - 'v*'
#   branches: 
#       - master
    schedule:
        - cron: 0 18 * * *
#   watch:
#       types: [started]
    workflow_dispatch:

jobs:
  update_singboxp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Auto update singbox_core_PuerNya to prerelease
      uses: ./.github/workflows/update_singbox_core.yaml
      with:
        tag1: PuerNya/sing-box
        tag2: building
        tag3: singbox_core_PuerNya
        tag5: with_quic,with_dhcp,with_wireguard,with_shadowsocksr,with_ech,with_utls,with_clash_api,with_gvisor
        