name: core_auto_update

on: 
    schedule:
        - cron: 0 18 * * *
    workflow_dispatch:
        
jobs:
  update_singboxp:
    runs-on: ubuntu-latest
    steps:
      - name: Auto update singbox_core_PuerNya to prerelease
        uses: actions/github-script@v7
        with:
          script: |
            const { Octokit } = require("@octokit/core");

            const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

            const { data: { id } } = await octokit.request('GET /repos/{owner}/{repo}/actions/workflows', {
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            await octokit.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'update_singbox_core.yaml',
              ref: 'dev',
              inputs: {
                tag1: 'PuerNya/sing-box',
                tag2: 'building',
                tag3: 'singbox_core_PuerNya',
                tag5: 'with_quic,with_dhcp,with_wireguard,with_shadowsocksr,with_ech,with_utls,with_clash_api,with_gvisor'            
              }
            });
