name: core_auto_update

on: 
    schedule:
        - cron: 0 18 * * *
    workflow_dispatch:

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - name: Get old version
        run: |
          version_old=$(curl -sSl https://github.com/juewuy/ShellCrash/releases/download/singbox_core_PuerNya/version) 
          echo version_old=$version_old >> "$GITHUB_OUTPUT"
        
      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: PuerNya/sing-box
          ref: building
          fetch-depth: 0   
      - name: Get new version    
        run: |
          git remote add sekai https://github.com/SagerNet/sing-box.git
          git fetch --tags sekai
          version_new=$(CGO_ENABLED=0 go run ./cmd/internal/read_tag)
          echo version_new=$version_new >> "$GITHUB_OUTPUT"    
    
  auto_update_singboxp_with_wg:
    needs: check_version
    if: ${{ needs.check_version.outputs.version_new != needs.check_version.outputs.version_old }}
    permissions: write-all
    uses: juewuy/ShellCrash/.github/workflows/update_singbox_core.yaml@dev
    with:
      tag1: PuerNya/sing-box
      tag2: building
      tag3: singbox_core_PuerNya
      tag5: with_quic,with_dhcp,with_wireguard,with_shadowsocksr,with_ech,with_utls,with_clash_api,with_gvisor
    secrets: inherit

  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: cleanup
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 2   
