name: Test Sing-Box Core for ShellCrash

on:
  workflow_dispatch:
    inputs:
      tag1:
        description: 'project name of sing-box, such as SagerNet/sing-box'
        required: true
        type: string
      tag2:
        description: 'tag or branches of sing-box, such as v1.7.8 or dev-next'
        required: true
        type: string
      tag3:
        description: 'a new prerelease name or not，such as _PuerNya'
        required: false
        type: string
jobs:
  cross:
    strategy:
      matrix:
        include:
          # linux
          - name: linux-amd64
            goos: linux
            goarch: amd64
            goamd64: v1
          - name: linux-386
            goos: linux
            goarch: 386
          - name: linux-arm64
            goos: linux
            goarch: arm64
          - name: linux-armv5
            goos: linux
            goarch: arm
            goarm: 5
          - name: linux-armv7
            goos: linux
            goarch: arm
            goarm: 7
          - name: linux-mips-softfloat
            goos: linux
            goarch: mips
            gomips: softfloat
          - name: linux-mipsel-softfloat
            goos: linux
            goarch: mipsle
            gomips: softfloat
          - name: linux-mipsel-hardfloat
            goos: linux
            goarch: mipsle
            gomips: hardfloat   

      fail-fast: false
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOAMD64: ${{ matrix.goamd64 }}
      GOARM: ${{ matrix.goarm }}
      GOMIPS: ${{ matrix.gomips }}
      CGO_ENABLED: 0
      TAGS: with_quic,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api
    steps:
      - name: Checkout sing-box
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          repository: ${{ github.event.inputs.tag1 }}
          ref: ${{ github.event.inputs.tag2 }}
          fetch-depth: 0
      - name: Get latest go version
        id: version
        run: |
          echo go_version=$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g') >> $GITHUB_OUTPUT
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.version.outputs.go_version }}
      - name: Build
        id: build
        run: make
      - name: Upload file to workspace
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: sing-box
  push_prerelease:
    needs: cross
    runs-on: ubuntu-latest
    steps:
      - name: Get upx
        run: |
          wget https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz
          wget https://github.com/upx/upx/releases/download/v3.93/upx-3.93-amd64_linux.tar.xz
          tar xf upx-3.96-amd64_linux.tar.xz
          tar xf upx-3.93-amd64_linux.tar.xz
      - name: Download file from workspace
        uses: actions/download-artifact@v4
        with:
          path: ./tmp
      - name: Zip core by upx
        run: |      
          archs=(amd64 armv5 armv7 arm64 mips-softfloat mipsel-hardfloat mipsel-softfloat)
          new_name=(amd64 armv5 armv7 armv8 mips-softfloat mipsle-hardfloat mipsle-softfloat)
          for((i=0;i<7;i++));do
            mv -f ./tmp/linux-${archs[i]}/sing-box ./tmp/singbox-linux-${new_name[i]}
            chmod +x ./tmp/singbox-linux-${new_name[i]}
            if [ "${archs[i]}" != "armv5" ];then
              if [[ ${archs[i]} = mips* ]];then
                ./upx-3.93-amd64_linux/upx ./tmp/singbox-linux-${new_name[i]}
              else
                ./upx-3.96-amd64_linux/upx ./tmp/singbox-linux-${new_name[i]}
              fi
            fi
          done
          rm -fr upx*  
          rm -fr ./tmp/core.tar.gz
          echo ${{ github.event.inputs.tag2 }} > ./tmp/version
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: singbox_core${{ github.event.inputs.tag3 }}
          name: singbox_core${{ github.event.inputs.tag3 }}
          body: "The ${{ github.event.inputs.tag2 }} version of ${{ github.event.inputs.tag1 }} \n这是${{ github.event.inputs.tag1 }}的${{ github.event.inputs.tag2 }}版本内核文件\nhttps://github.com/${{ github.event.inputs.tag1 }}/releases \nZip by upx\n使用了upx进行压缩\nOnly support for ShellCrash\n仅限于ShellCrash项目使用"
          draft: false
          prerelease: true
          files: |
            ./tmp/* 
      - name: Cleanup Workflow
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 2      
